### ISSUE TITLE
A bug in rl_eval.sh

### ISSUE THREAD

**Issue by Norweig1an** [tianhaowuhz/human-assisting-dex-grasp#1]
Traceback (most recent call last):
  File "./Runners/EvalGFPPO.py", line 82, in <module>
    runner.run(num_learning_iterations=iterations, log_interval=cfg_train["learn"]["save_interval"])
  File "./Algorithms/ppo/gf_ppo_update.py", line 379, in run
    self.eval(0)
  File "./Algorithms/ppo/gf_ppo_update.py", line 292, in eval
    actions, grad = self.compute_action(current_obs=current_obs,mode='eval')
  File "./Algorithms/ppo/gf_ppo_update.py", line 765, in compute_action
    actions_batch = self.actor_critic.act_inference(current_obs_batch)
  File "./Algorithms/ppo/module.py", line 589, in act_inference
    actions_mean = self.forward_actor(observations)
  File "./Algorithms/ppo/module.py", line 334, in forward_actor
    obj_feat, _, _ = self.pointnet_enc(obj_batch.reshape(batch_size,3,-1))
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 3, -1] because the unspecified dimension size -1 can be any value and is ambiguous
Segmentation fault (core dumped)

**Comment by Norweig1an** [comment]
Also, could you provide the visualizer shell? Reading the code to comprehend your process is a little challenging.
Thanks!

**Comment by tianhaowuhz** [comment]
> Also, could you provide the visualizer shell? Reading the code to comprehend your process is a little challenging. Thanks!

what kind of visualizer shell do you mean?
