### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for CondScoreModel:

### ISSUE THREAD

**Issue by liuqi8827** [tianhaowuhz/human-assisting-dex-grasp#5]
I followed the readme:
1. Training the GraspGF.
2. Pretrain the pointnet for RL. **Then, I got the pt.pt and score.pt.** And I put pt.pt and score.pt in the folder: '/home/lq/codes/human-assisting-dex-grasp/Ckpt/gf_lq'. 
3. However, when I ran `sh ./rl_train.sh`, the error occurred:
Traceback (most recent call last):
  File "./Runners/TrainGFPPO.py", line 77, in <module>
    runner = GFPPO(vec_env=envs,
  File "/home/lq/codes/human-assisting-dex-grasp/./Algorithms/ppo/gf_ppo_update.py", line 178, in __init__
    self.score.load_state_dict(model_dict)
  File "/home/lq/miniconda3/envs/dexgrasp-py38-new/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CondScoreModel:
	Missing key(s) in state_dict: "obj_enc.sa1.mlps.0.layer0.conv.weight", "obj_enc.sa1.mlps.0.layer0.bn.bn.weight", "obj_enc.sa1.mlps.0.layer0.bn.bn.bias", "obj_enc.sa1.mlps.0.layer0.bn.bn.running_mean", "obj_enc.sa1.mlps.0.layer0.bn.bn.running_var", "obj_enc.sa1.mlps.0.layer1.conv.weight", "obj_enc.sa1.mlps.0.layer1.bn.bn.weight", "obj_enc.sa1.mlps.0.layer1.bn.bn.bias", "obj_enc.sa1.mlps.0.layer1.bn.bn.running_mean", "obj_enc.sa1.mlps.0.layer1.bn.bn.running_var", "obj_enc.sa1.mlps.0.layer2.conv.weight", "obj_enc.sa1.mlps.0.layer2.bn.bn.weight", "obj_enc.sa1.mlps.0.layer2.bn.bn.bias", "obj_enc.sa1.mlps.0.layer2.bn.bn.running_mean", "obj_enc.sa1.mlps.0.layer2.bn.bn.running_var", "obj_enc.sa2.mlps.0.layer0.conv.weight", "obj_enc.sa2.mlps.0.layer0.bn.bn.weight", "obj_enc.sa2.mlps.0.layer0.bn.bn.bias", "obj_enc.sa2.mlps.0.layer0.bn.bn.running_mean", "obj_enc.sa2.mlps.0.layer0.bn.bn.running_var", "obj_enc.sa2.mlps.0.layer1.conv.weight", "obj_enc.sa2.mlps.0.layer1.bn.bn.weight", "obj_enc.sa2.mlps.0.layer1.bn.bn.bias", "obj_enc.sa2.mlps.0.layer1.bn.bn.running_mean", "obj_enc.sa2.mlps.0.layer1.bn.bn.running_var", "obj_enc.sa2.mlps.0.layer2.conv.weight", "obj_enc.sa2.mlps.0.layer2.bn.bn.weight", "obj_enc.sa2.mlps.0.layer2.bn.bn.bias", "obj_enc.sa2.mlps.0.layer2.bn.bn.running_mean", "obj_enc.sa2.mlps.0.layer2.bn.bn.running_var", "obj_enc.sa3.mlps.0.layer0.conv.weight", "obj_enc.sa3.mlps.0.layer0.bn.bn.weight", "obj_enc.sa3.mlps.0.layer0.bn.bn.bias", "obj_enc.sa3.mlps.0.layer0.bn.bn.running_mean", "obj_enc.sa3.mlps.0.layer0.bn.bn.running_var", "obj_enc.sa3.mlps.0.layer1.conv.weight", "obj_enc.sa3.mlps.0.layer1.bn.bn.weight", "obj_enc.sa3.mlps.0.layer1.bn.bn.bias", "obj_enc.sa3.mlps.0.layer1.bn.bn.running_mean", "obj_enc.sa3.mlps.0.layer1.bn.bn.running_var", "obj_enc.sa3.mlps.0.layer2.conv.weight", "obj_enc.sa3.mlps.0.layer2.bn.bn.weight", "obj_enc.sa3.mlps.0.layer2.bn.bn.bias", "obj_enc.sa3.mlps.0.layer2.bn.bn.running_mean", "obj_enc.sa3.mlps.0.layer2.bn.bn.running_var". 
	Unexpected key(s) in state_dict: "obj_enc.stn.conv1.weight", "obj_enc.stn.conv1.bias", "obj_enc.stn.conv2.weight", "obj_enc.stn.conv2.bias", "obj_enc.stn.conv3.weight", "obj_enc.stn.conv3.bias", "obj_enc.stn.fc1.weight", "obj_enc.stn.fc1.bias", "obj_enc.stn.fc2.weight", "obj_enc.stn.fc2.bias", "obj_enc.stn.fc3.weight", "obj_enc.stn.fc3.bias", "obj_enc.conv1.weight", "obj_enc.conv1.bias", "obj_enc.conv2.weight", "obj_enc.conv2.bias", "obj_enc.conv3.weight", "obj_enc.conv3.bias", "obj_enc.conv4.weight", "obj_enc.conv4.bias".
![image](https://github.com/user-attachments/assets/e8509f8c-d1a6-45a5-bd1b-ff15927c1878)
**这个错误表明在加载 `state_dict` 时，模型的结构与保存的权重不匹配。具体来说，有一些键在 `state_dict` 中缺失，而另一些键是多余的。**
4. The command in shell "rl_train.sh" is:
python ./Runners/TrainGFPPO.py \
--seed=0 \
--headless \
--num_envs=100 \
--dataset_type='train' \
--score_model_path='/home/lq/codes/human-assisting-dex-grasp/Ckpt/gf_lq' \
--t0=0.005 \
--exp_name="ours" \
--run_device_id=0 \
--constrained \
6. I can successfully run `sh ./rl_train.sh` with the pretrained checkpoint (https://drive.google.com/drive/folders/1-_AcEFnnVO9g-CeCPyjleuDYrUdxXtyd) you gave in the readme. And the command in shell "rl_train.sh" is:
python ./Runners/TrainGFPPO.py \
--seed=0 \
--headless \
--num_envs=100 \
--dataset_type='train' \
--score_model_path='/home/lq/codes/human-assisting-dex-grasp/Ckpt/gf' \
--t0=0.005 \
--exp_name="ours" \
--run_device_id=0 \
--constrained \

The `rl_train` process is successful with your pretrained checkpoint:
![image](https://github.com/user-attachments/assets/4a123a45-5b36-4b99-aa78-4bf6e5586517)

7. Can you give some suggestions?

**Comment by liuqi8827** [comment]
I run it successfully.
